database:
  type: h2
  mysql:
    host: localhost
    port: 3306
    database: landsapi
    username: admin
    password: landsapi
    params:
      - autoReconnect=true
      - useSSL=false
  postgresql:
    host: localhost
    port: 5432
    database: landsapi
    username: admin
    password: landsapi
    params:
      - autoReconnect=true
      - useSSL=false
  h2:
    file: database
  sqlite:
    file: database.db
